# Generated by Django 5.0.6 on 2024-05-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VDSTDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('vat_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('vat_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tax_image1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tax_image2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('tax_image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('vat_Service_code', models.TextField(blank=True, max_length=100, null=True)),
                ('vat_VAT_rate', models.TextField(blank=True, max_length=100, null=True)),
                ('vat_VDS', models.TextField(blank=True, max_length=100, null=True)),
                ('vat_remarks1', models.TextField(blank=True, max_length=100, null=True)),
                ('vat_remarks2', models.TextField(blank=True, max_length=100, null=True)),
                ('tax_Section', models.TextField(blank=True, max_length=100, null=True)),
                ('tax_subsection', models.TextField(blank=True, max_length=100, null=True)),
                ('tax_TDS_rate', models.TextField(blank=True, max_length=100, null=True)),
                ('tax_remark1', models.TextField(blank=True, max_length=100, null=True)),
                ('tax_remark2', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
