# Generated by Django 5.0.6 on 2024-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdstds',
            name='vat_VDS',
            field=models.TextField(blank=True, default='Mandatory', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vdstds',
            name='vat_remarks1',
            field=models.TextField(blank=True, default='Mushok 6.3 must be issued', max_length=100, null=True),
        ),
    ]
