# Generated by Django 5.0.6 on 2024-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_vdstds_vat_vds_alter_vdstds_vat_remarks1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdstds',
            name='vat_remarks1',
            field=models.TextField(blank=True, default='Mushok 6.3 must be issued', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vdstds',
            name='vat_remarks2',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
