# Generated by Django 5.0.6 on 2024-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vdstds_vat_remarks1_alter_vdstds_vat_remarks2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdstds',
            name='tax_remark1',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vdstds',
            name='tax_remark2',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
