# Generated by Django 5.0.6 on 2024-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vdstds_tax_remark1_alter_vdstds_tax_remark2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vdstds',
            name='tax_remark1',
            field=models.TextField(blank=True, default='If any valid non-deduction certificate (issued by NBR) is furnished,  TDS could be waived as per instruction.', max_length=150, null=True),
        ),
    ]
