# Generated by Django 5.0.6 on 2024-05-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_vdstds_tax_remark1'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsers/')),
            ],
        ),
    ]
