# Generated by Django 5.0.6 on 2024-06-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sponsers'),
    ]

    operations = [
        migrations.AddField(
            model_name='vdstds',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
