# Generated by Django 5.0.6 on 2024-06-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_vdstds_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='renews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
