# Generated by Django 5.0.6 on 2024-06-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_pot_delete_renews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pot',
        ),
    ]
