# Generated by Django 5.0.6 on 2024-05-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
