# Generated by Django 5.0.6 on 2024-06-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_users_activation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
