# Generated by Django 5.0.6 on 2024-06-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='renew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=11, null=True, unique=True)),
            ],
        ),
    ]
