# Generated by Django 5.0.6 on 2024-06-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_renew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='renew',
        ),
    ]
