# Generated by Django 5.0.6 on 2024-06-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_delete_renew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
