# Generated by Django 5.0.6 on 2024-06-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='trial_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
